//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSReportGen.BANKS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BANKS.bankSoap")]
    public interface bankSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBalForDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getBalForDate(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code, System.DateTime sd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBalForDate", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getBalForDateAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code, System.DateTime sd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAvgBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getAvgBalance(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAvgBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getAvgBalanceAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAvgBalanceTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAvgBalanceTable(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAvgBalanceTable", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAvgBalanceTableAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAvgBalanceTableMonth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAvgBalanceTableMonth(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code, int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAvgBalanceTableMonth", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getAvgBalanceTableMonthAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code, int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAccountInfo(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAccountInfoAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountInfo2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAccountInfo2(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountInfo2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAccountInfo2Async(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool getAccountStatus(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> getAccountStatusAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getRates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRates", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getRatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountByNUBAN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAccountByNUBAN(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountByNUBAN", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAccountByNUBANAsync(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHumanManagerInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getHumanManagerInfo(string staffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHumanManagerInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getHumanManagerInfoAsync(string staffID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHumanManagerDepartments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getHumanManagerDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHumanManagerDepartments", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getHumanManagerDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHumanManagerFunctions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getHumanManagerFunctions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHumanManagerFunctions", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getHumanManagerFunctionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHumanManagerGrades", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getHumanManagerGrades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHumanManagerGrades", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getHumanManagerGradesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBankLedgers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getBankLedgers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBankLedgers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getBankLedgersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAccount(string accnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAccountAsync(string accnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getAccountName(string accnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getAccountNameAsync(string accnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountFromNUBAN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getAccountFromNUBAN(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountFromNUBAN", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getAccountFromNUBANAsync(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountFromNUBAN2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getAccountFromNUBAN2(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountFromNUBAN2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getAccountFromNUBAN2Async(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBalanceDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getBalanceDetails(string acctnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBalanceDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getBalanceDetailsAsync(string acctnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCusBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getCusBalance(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCusBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getCusBalanceAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCusBal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getCusBal(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCusBal", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getCusBalAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkOpLedger", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet checkOpLedger(string led_code, string ext_tra_flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkOpLedger", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> checkOpLedgerAsync(string led_code, string ext_tra_flag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkCusAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool checkCusAccount(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkCusAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> checkCusAccountAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTellerLimit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getTellerLimit(string tell_id, string bra_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTellerLimit", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getTellerLimitAsync(string tell_id, string bra_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNubanAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getNubanAccount(string Nubannum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNubanAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getNubanAccountAsync(string Nubannum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNuban", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getNuban(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNuban", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getNubanAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CusInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CusInfo(string accnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CusInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CusInfoAsync(string accnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CusInfo1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CusInfo1(string bracode, string cusnum, string curcode, string ledcode, string subacctcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CusInfo1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CusInfo1Async(string bracode, string cusnum, string curcode, string ledcode, string subacctcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CusInfo2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CusInfo2(string bracode, string cusnum, string curcode, string ledcode, string subacctcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CusInfo2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CusInfo2Async(string bracode, string cusnum, string curcode, string ledcode, string subacctcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAccountDetails(string acctnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAccountDetailsAsync(string acctnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITellerDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ITellerDetails(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITellerDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ITellerDetailsAsync(string nuban);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountFullinfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAccountFullinfo(string acctnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccountFullinfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAccountFullinfoAsync(string acctnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateChq", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool validateChq(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validateChq", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> validateChqAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isChequeUsed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool isChequeUsed(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isChequeUsed", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> isChequeUsedAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HasDetailsBeenPosted", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool HasDetailsBeenPosted(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum, decimal amtVal, System.DateTime value_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HasDetailsBeenPosted", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> HasDetailsBeenPostedAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum, decimal amtVal, System.DateTime value_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetailsWithValuedate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DetailsWithValuedate(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum, decimal amtVal, System.DateTime value_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DetailsWithValuedate", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DetailsWithValuedateAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum, decimal amtVal, System.DateTime value_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBranches", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getBranches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBranches", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getBranchesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBankNames", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getBankNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBankNames", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getBankNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getParallexCashDepotsitBankDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getParallexCashDepotsitBankDetails(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string origt_tra_seq1, string tra_amt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getParallexCashDepotsitBankDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getParallexCashDepotsitBankDetailsAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string origt_tra_seq1, string tra_amt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getParallexChqBankDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getParallexChqBankDetails(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string doc_num, string tra_amt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getParallexChqBankDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getParallexChqBankDetailsAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string doc_num, string tra_amt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsChequeDetailsonBanks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet IsChequeDetailsonBanks(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum, decimal amtVal, System.DateTime value_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsChequeDetailsonBanks", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> IsChequeDetailsonBanksAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum, decimal amtVal, System.DateTime value_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet checkAccount(string mobile, string accnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> checkAccountAsync(string mobile, string accnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet checkMobile(string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkMobile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> checkMobileAsync(string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSMSAlertUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getSMSAlertUser(string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSMSAlertUser", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getSMSAlertUserAsync(string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getBalance(string accno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getBalanceAsync(string accno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBranchName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getBranchName(string bracode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBranchName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getBranchNameAsync(string bracode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBalance2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getBalance2(string bracode, string cusnum, string curcode, string ledcode, string subacctcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBalance2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getBalance2Async(string bracode, string cusnum, string curcode, string ledcode, string subacctcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStatement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getStatement(string bra_code, string cus_num, string cur_code, string led_code, string sub_code, string rowCnt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStatement", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getStatementAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_code, string rowCnt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSMSAlertReg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool getSMSAlertReg(string mobile, string accnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSMSAlertReg", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> getSMSAlertRegAsync(string mobile, string accnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccount2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SRSReportGen.BANKS.Account getAccount2(string accnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccount2", ReplyAction="*")]
        System.Threading.Tasks.Task<SRSReportGen.BANKS.Account> getAccount2Async(string accnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFullAcct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getFullAcct(string Nubannum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFullAcct", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getFullAcctAsync(string Nubannum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/gettellerstatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool gettellerstatus(string tellid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/gettellerstatus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> gettellerstatusAsync(string tellid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkTellerRole", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool checkTellerRole(string bra_code, string tellid, int roleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkTellerRole", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> checkTellerRoleAsync(string bra_code, string tellid, int roleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFullAcctName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getFullAcctName(string acctnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFullAcctName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getFullAcctNameAsync(string acctnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSTACODE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getSTACODE(string bracode, string cusnum, string curcode, string ledcode, string subacctcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSTACODE", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getSTACODEAsync(string bracode, string cusnum, string curcode, string ledcode, string subacctcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getCHE_DIG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DATCONV_getCHE_DIG(string cusnum, string bracode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getCHE_DIG", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DATCONV_getCHE_DIGAsync(string cusnum, string bracode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getCustomerName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DATCONV_getCustomerName(string cusnum, string bracode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getCustomerName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DATCONV_getCustomerNameAsync(string cusnum, string bracode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getOVERDRAWN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DATCONV_getOVERDRAWN(string ledcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getOVERDRAWN", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DATCONV_getOVERDRAWNAsync(string ledcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReportsPortalDDL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReportsPortalDDL(string strsql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReportsPortalDDL", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReportsPortalDDLAsync(string strsql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReportsPortalDML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReportsPortalDML(string storedProcedure, string fromDate, string toDate, string bracode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReportsPortalDML", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReportsPortalDMLAsync(string storedProcedure, string fromDate, string toDate, string bracode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReportsPortalSQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReportsPortalSQL(string connstr, string strsql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReportsPortalSQL", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReportsPortalSQLAsync(string connstr, string strsql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getUNPROCESSED", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DATCONV_getUNPROCESSED(string dater);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getUNPROCESSED", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DATCONV_getUNPROCESSEDAsync(string dater);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getREPORT29", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet DATCONV_getREPORT29(string dater, string compcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getREPORT29", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> DATCONV_getREPORT29Async(string dater, string compcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCustomeronSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getCustomeronSMS(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCustomeronSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getCustomeronSMSAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getRESTIND", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DATCONV_getRESTIND(string cusnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getRESTIND", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DATCONV_getRESTINDAsync(string cusnum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getDESENG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DATCONV_getDESENG(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getDESENG", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DATCONV_getDESENGAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getBracodeFromTellerId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DATCONV_getBracodeFromTellerId(string tellerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DATCONV_getBracodeFromTellerId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DATCONV_getBracodeFromTellerIdAsync(string tellerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSREM_delTxn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CUSREM_delTxn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSREM_delTxn", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CUSREM_delTxnAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSREM_InsertTxn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CUSREM_InsertTxn(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code, string cname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSREM_InsertTxn", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CUSREM_InsertTxnAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code, string cname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSREM_getCustomerRecs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CUSREM_getCustomerRecs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSREM_getCustomerRecs", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CUSREM_getCustomerRecsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSREM_process", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CUSREM_process();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSREM_process", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CUSREM_processAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSREM_process2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CUSREM_process2(long BRACODE, long CUSNUM, long CURCODE, long LEDCODE, long SUBACCTCODE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUSREM_process2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CUSREM_process2Async(long BRACODE, long CUSNUM, long CURCODE, long LEDCODE, long SUBACCTCODE);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Account : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bra_codeField;
        
        private string cus_numField;
        
        private string cur_codeField;
        
        private string led_codeField;
        
        private string sub_acct_codeField;
        
        private string cus_sho_nameField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bra_code {
            get {
                return this.bra_codeField;
            }
            set {
                this.bra_codeField = value;
                this.RaisePropertyChanged("bra_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cus_num {
            get {
                return this.cus_numField;
            }
            set {
                this.cus_numField = value;
                this.RaisePropertyChanged("cus_num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cur_code {
            get {
                return this.cur_codeField;
            }
            set {
                this.cur_codeField = value;
                this.RaisePropertyChanged("cur_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string led_code {
            get {
                return this.led_codeField;
            }
            set {
                this.led_codeField = value;
                this.RaisePropertyChanged("led_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string sub_acct_code {
            get {
                return this.sub_acct_codeField;
            }
            set {
                this.sub_acct_codeField = value;
                this.RaisePropertyChanged("sub_acct_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string cus_sho_name {
            get {
                return this.cus_sho_nameField;
            }
            set {
                this.cus_sho_nameField = value;
                this.RaisePropertyChanged("cus_sho_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface bankSoapChannel : SRSReportGen.BANKS.bankSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class bankSoapClient : System.ServiceModel.ClientBase<SRSReportGen.BANKS.bankSoap>, SRSReportGen.BANKS.bankSoap {
        
        public bankSoapClient() {
        }
        
        public bankSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public bankSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bankSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public bankSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double getBalForDate(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code, System.DateTime sd) {
            return base.Channel.getBalForDate(bra_code, cus_num, cur_code, led_code, sub_acct_code, sd);
        }
        
        public System.Threading.Tasks.Task<double> getBalForDateAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code, System.DateTime sd) {
            return base.Channel.getBalForDateAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code, sd);
        }
        
        public double getAvgBalance(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code) {
            return base.Channel.getAvgBalance(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Threading.Tasks.Task<double> getAvgBalanceAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code) {
            return base.Channel.getAvgBalanceAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Data.DataTable getAvgBalanceTable(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code) {
            return base.Channel.getAvgBalanceTable(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAvgBalanceTableAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code) {
            return base.Channel.getAvgBalanceTableAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Data.DataTable getAvgBalanceTableMonth(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code, int year, int month) {
            return base.Channel.getAvgBalanceTableMonth(bra_code, cus_num, cur_code, led_code, sub_acct_code, year, month);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getAvgBalanceTableMonthAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code, int year, int month) {
            return base.Channel.getAvgBalanceTableMonthAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code, year, month);
        }
        
        public System.Data.DataSet getAccountInfo(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code) {
            return base.Channel.getAccountInfo(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAccountInfoAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code) {
            return base.Channel.getAccountInfoAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Data.DataSet getAccountInfo2(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code) {
            return base.Channel.getAccountInfo2(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAccountInfo2Async(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code) {
            return base.Channel.getAccountInfo2Async(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public bool getAccountStatus(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code) {
            return base.Channel.getAccountStatus(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Threading.Tasks.Task<bool> getAccountStatusAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code) {
            return base.Channel.getAccountStatusAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Data.DataSet getRates() {
            return base.Channel.getRates();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getRatesAsync() {
            return base.Channel.getRatesAsync();
        }
        
        public System.Data.DataSet getAccountByNUBAN(string nuban) {
            return base.Channel.getAccountByNUBAN(nuban);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAccountByNUBANAsync(string nuban) {
            return base.Channel.getAccountByNUBANAsync(nuban);
        }
        
        public System.Data.DataTable getHumanManagerInfo(string staffID) {
            return base.Channel.getHumanManagerInfo(staffID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getHumanManagerInfoAsync(string staffID) {
            return base.Channel.getHumanManagerInfoAsync(staffID);
        }
        
        public System.Data.DataTable getHumanManagerDepartments() {
            return base.Channel.getHumanManagerDepartments();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getHumanManagerDepartmentsAsync() {
            return base.Channel.getHumanManagerDepartmentsAsync();
        }
        
        public System.Data.DataTable getHumanManagerFunctions() {
            return base.Channel.getHumanManagerFunctions();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getHumanManagerFunctionsAsync() {
            return base.Channel.getHumanManagerFunctionsAsync();
        }
        
        public System.Data.DataTable getHumanManagerGrades() {
            return base.Channel.getHumanManagerGrades();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getHumanManagerGradesAsync() {
            return base.Channel.getHumanManagerGradesAsync();
        }
        
        public System.Data.DataSet getBankLedgers() {
            return base.Channel.getBankLedgers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getBankLedgersAsync() {
            return base.Channel.getBankLedgersAsync();
        }
        
        public System.Data.DataSet getAccount(string accnum) {
            return base.Channel.getAccount(accnum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAccountAsync(string accnum) {
            return base.Channel.getAccountAsync(accnum);
        }
        
        public string getAccountName(string accnum) {
            return base.Channel.getAccountName(accnum);
        }
        
        public System.Threading.Tasks.Task<string> getAccountNameAsync(string accnum) {
            return base.Channel.getAccountNameAsync(accnum);
        }
        
        public string getAccountFromNUBAN(string nuban) {
            return base.Channel.getAccountFromNUBAN(nuban);
        }
        
        public System.Threading.Tasks.Task<string> getAccountFromNUBANAsync(string nuban) {
            return base.Channel.getAccountFromNUBANAsync(nuban);
        }
        
        public string getAccountFromNUBAN2(string nuban) {
            return base.Channel.getAccountFromNUBAN2(nuban);
        }
        
        public System.Threading.Tasks.Task<string> getAccountFromNUBAN2Async(string nuban) {
            return base.Channel.getAccountFromNUBAN2Async(nuban);
        }
        
        public System.Data.DataSet getBalanceDetails(string acctnum) {
            return base.Channel.getBalanceDetails(acctnum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getBalanceDetailsAsync(string acctnum) {
            return base.Channel.getBalanceDetailsAsync(acctnum);
        }
        
        public System.Data.DataSet getCusBalance(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code) {
            return base.Channel.getCusBalance(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getCusBalanceAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code) {
            return base.Channel.getCusBalanceAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Data.DataSet getCusBal(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code) {
            return base.Channel.getCusBal(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getCusBalAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code) {
            return base.Channel.getCusBalAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Data.DataSet checkOpLedger(string led_code, string ext_tra_flag) {
            return base.Channel.checkOpLedger(led_code, ext_tra_flag);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> checkOpLedgerAsync(string led_code, string ext_tra_flag) {
            return base.Channel.checkOpLedgerAsync(led_code, ext_tra_flag);
        }
        
        public bool checkCusAccount(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code) {
            return base.Channel.checkCusAccount(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Threading.Tasks.Task<bool> checkCusAccountAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code) {
            return base.Channel.checkCusAccountAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Data.DataSet getTellerLimit(string tell_id, string bra_code) {
            return base.Channel.getTellerLimit(tell_id, bra_code);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getTellerLimitAsync(string tell_id, string bra_code) {
            return base.Channel.getTellerLimitAsync(tell_id, bra_code);
        }
        
        public System.Data.DataSet getNubanAccount(string Nubannum) {
            return base.Channel.getNubanAccount(Nubannum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getNubanAccountAsync(string Nubannum) {
            return base.Channel.getNubanAccountAsync(Nubannum);
        }
        
        public System.Data.DataSet getNuban(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code) {
            return base.Channel.getNuban(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getNubanAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code) {
            return base.Channel.getNubanAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Data.DataSet CusInfo(string accnum) {
            return base.Channel.CusInfo(accnum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CusInfoAsync(string accnum) {
            return base.Channel.CusInfoAsync(accnum);
        }
        
        public System.Data.DataSet CusInfo1(string bracode, string cusnum, string curcode, string ledcode, string subacctcode) {
            return base.Channel.CusInfo1(bracode, cusnum, curcode, ledcode, subacctcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CusInfo1Async(string bracode, string cusnum, string curcode, string ledcode, string subacctcode) {
            return base.Channel.CusInfo1Async(bracode, cusnum, curcode, ledcode, subacctcode);
        }
        
        public System.Data.DataSet CusInfo2(string bracode, string cusnum, string curcode, string ledcode, string subacctcode) {
            return base.Channel.CusInfo2(bracode, cusnum, curcode, ledcode, subacctcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CusInfo2Async(string bracode, string cusnum, string curcode, string ledcode, string subacctcode) {
            return base.Channel.CusInfo2Async(bracode, cusnum, curcode, ledcode, subacctcode);
        }
        
        public System.Data.DataSet getAccountDetails(string acctnum) {
            return base.Channel.getAccountDetails(acctnum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAccountDetailsAsync(string acctnum) {
            return base.Channel.getAccountDetailsAsync(acctnum);
        }
        
        public System.Data.DataSet ITellerDetails(string nuban) {
            return base.Channel.ITellerDetails(nuban);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ITellerDetailsAsync(string nuban) {
            return base.Channel.ITellerDetailsAsync(nuban);
        }
        
        public System.Data.DataSet getAccountFullinfo(string acctnum) {
            return base.Channel.getAccountFullinfo(acctnum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAccountFullinfoAsync(string acctnum) {
            return base.Channel.getAccountFullinfoAsync(acctnum);
        }
        
        public bool validateChq(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum) {
            return base.Channel.validateChq(bra_code, cus_num, cur_code, led_code, sub_acct_code, docnum);
        }
        
        public System.Threading.Tasks.Task<bool> validateChqAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum) {
            return base.Channel.validateChqAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code, docnum);
        }
        
        public bool isChequeUsed(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum) {
            return base.Channel.isChequeUsed(bra_code, cus_num, cur_code, led_code, sub_acct_code, docnum);
        }
        
        public System.Threading.Tasks.Task<bool> isChequeUsedAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum) {
            return base.Channel.isChequeUsedAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code, docnum);
        }
        
        public bool HasDetailsBeenPosted(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum, decimal amtVal, System.DateTime value_date) {
            return base.Channel.HasDetailsBeenPosted(bra_code, cus_num, cur_code, led_code, sub_acct_code, docnum, amtVal, value_date);
        }
        
        public System.Threading.Tasks.Task<bool> HasDetailsBeenPostedAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum, decimal amtVal, System.DateTime value_date) {
            return base.Channel.HasDetailsBeenPostedAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code, docnum, amtVal, value_date);
        }
        
        public bool DetailsWithValuedate(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum, decimal amtVal, System.DateTime value_date) {
            return base.Channel.DetailsWithValuedate(bra_code, cus_num, cur_code, led_code, sub_acct_code, docnum, amtVal, value_date);
        }
        
        public System.Threading.Tasks.Task<bool> DetailsWithValuedateAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum, decimal amtVal, System.DateTime value_date) {
            return base.Channel.DetailsWithValuedateAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code, docnum, amtVal, value_date);
        }
        
        public System.Data.DataSet getBranches() {
            return base.Channel.getBranches();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getBranchesAsync() {
            return base.Channel.getBranchesAsync();
        }
        
        public System.Data.DataSet getBankNames() {
            return base.Channel.getBankNames();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getBankNamesAsync() {
            return base.Channel.getBankNamesAsync();
        }
        
        public System.Data.DataSet getParallexCashDepotsitBankDetails(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string origt_tra_seq1, string tra_amt) {
            return base.Channel.getParallexCashDepotsitBankDetails(bra_code, cus_num, cur_code, led_code, sub_acct_code, origt_tra_seq1, tra_amt);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getParallexCashDepotsitBankDetailsAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string origt_tra_seq1, string tra_amt) {
            return base.Channel.getParallexCashDepotsitBankDetailsAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code, origt_tra_seq1, tra_amt);
        }
        
        public System.Data.DataSet getParallexChqBankDetails(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string doc_num, string tra_amt) {
            return base.Channel.getParallexChqBankDetails(bra_code, cus_num, cur_code, led_code, sub_acct_code, doc_num, tra_amt);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getParallexChqBankDetailsAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string doc_num, string tra_amt) {
            return base.Channel.getParallexChqBankDetailsAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code, doc_num, tra_amt);
        }
        
        public System.Data.DataSet IsChequeDetailsonBanks(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum, decimal amtVal, System.DateTime value_date) {
            return base.Channel.IsChequeDetailsonBanks(bra_code, cus_num, cur_code, led_code, sub_acct_code, docnum, amtVal, value_date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> IsChequeDetailsonBanksAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code, string docnum, decimal amtVal, System.DateTime value_date) {
            return base.Channel.IsChequeDetailsonBanksAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code, docnum, amtVal, value_date);
        }
        
        public System.Data.DataSet checkAccount(string mobile, string accnum) {
            return base.Channel.checkAccount(mobile, accnum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> checkAccountAsync(string mobile, string accnum) {
            return base.Channel.checkAccountAsync(mobile, accnum);
        }
        
        public System.Data.DataSet checkMobile(string mobile) {
            return base.Channel.checkMobile(mobile);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> checkMobileAsync(string mobile) {
            return base.Channel.checkMobileAsync(mobile);
        }
        
        public System.Data.DataSet getSMSAlertUser(string mobile) {
            return base.Channel.getSMSAlertUser(mobile);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getSMSAlertUserAsync(string mobile) {
            return base.Channel.getSMSAlertUserAsync(mobile);
        }
        
        public System.Data.DataSet getBalance(string accno) {
            return base.Channel.getBalance(accno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getBalanceAsync(string accno) {
            return base.Channel.getBalanceAsync(accno);
        }
        
        public string getBranchName(string bracode) {
            return base.Channel.getBranchName(bracode);
        }
        
        public System.Threading.Tasks.Task<string> getBranchNameAsync(string bracode) {
            return base.Channel.getBranchNameAsync(bracode);
        }
        
        public string getBalance2(string bracode, string cusnum, string curcode, string ledcode, string subacctcode) {
            return base.Channel.getBalance2(bracode, cusnum, curcode, ledcode, subacctcode);
        }
        
        public System.Threading.Tasks.Task<string> getBalance2Async(string bracode, string cusnum, string curcode, string ledcode, string subacctcode) {
            return base.Channel.getBalance2Async(bracode, cusnum, curcode, ledcode, subacctcode);
        }
        
        public System.Data.DataSet getStatement(string bra_code, string cus_num, string cur_code, string led_code, string sub_code, string rowCnt) {
            return base.Channel.getStatement(bra_code, cus_num, cur_code, led_code, sub_code, rowCnt);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getStatementAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_code, string rowCnt) {
            return base.Channel.getStatementAsync(bra_code, cus_num, cur_code, led_code, sub_code, rowCnt);
        }
        
        public bool getSMSAlertReg(string mobile, string accnum) {
            return base.Channel.getSMSAlertReg(mobile, accnum);
        }
        
        public System.Threading.Tasks.Task<bool> getSMSAlertRegAsync(string mobile, string accnum) {
            return base.Channel.getSMSAlertRegAsync(mobile, accnum);
        }
        
        public SRSReportGen.BANKS.Account getAccount2(string accnum) {
            return base.Channel.getAccount2(accnum);
        }
        
        public System.Threading.Tasks.Task<SRSReportGen.BANKS.Account> getAccount2Async(string accnum) {
            return base.Channel.getAccount2Async(accnum);
        }
        
        public System.Data.DataSet getFullAcct(string Nubannum) {
            return base.Channel.getFullAcct(Nubannum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getFullAcctAsync(string Nubannum) {
            return base.Channel.getFullAcctAsync(Nubannum);
        }
        
        public bool gettellerstatus(string tellid) {
            return base.Channel.gettellerstatus(tellid);
        }
        
        public System.Threading.Tasks.Task<bool> gettellerstatusAsync(string tellid) {
            return base.Channel.gettellerstatusAsync(tellid);
        }
        
        public bool checkTellerRole(string bra_code, string tellid, int roleID) {
            return base.Channel.checkTellerRole(bra_code, tellid, roleID);
        }
        
        public System.Threading.Tasks.Task<bool> checkTellerRoleAsync(string bra_code, string tellid, int roleID) {
            return base.Channel.checkTellerRoleAsync(bra_code, tellid, roleID);
        }
        
        public System.Data.DataSet getFullAcctName(string acctnum) {
            return base.Channel.getFullAcctName(acctnum);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getFullAcctNameAsync(string acctnum) {
            return base.Channel.getFullAcctNameAsync(acctnum);
        }
        
        public string getSTACODE(string bracode, string cusnum, string curcode, string ledcode, string subacctcode) {
            return base.Channel.getSTACODE(bracode, cusnum, curcode, ledcode, subacctcode);
        }
        
        public System.Threading.Tasks.Task<string> getSTACODEAsync(string bracode, string cusnum, string curcode, string ledcode, string subacctcode) {
            return base.Channel.getSTACODEAsync(bracode, cusnum, curcode, ledcode, subacctcode);
        }
        
        public string DATCONV_getCHE_DIG(string cusnum, string bracode) {
            return base.Channel.DATCONV_getCHE_DIG(cusnum, bracode);
        }
        
        public System.Threading.Tasks.Task<string> DATCONV_getCHE_DIGAsync(string cusnum, string bracode) {
            return base.Channel.DATCONV_getCHE_DIGAsync(cusnum, bracode);
        }
        
        public string DATCONV_getCustomerName(string cusnum, string bracode) {
            return base.Channel.DATCONV_getCustomerName(cusnum, bracode);
        }
        
        public System.Threading.Tasks.Task<string> DATCONV_getCustomerNameAsync(string cusnum, string bracode) {
            return base.Channel.DATCONV_getCustomerNameAsync(cusnum, bracode);
        }
        
        public string DATCONV_getOVERDRAWN(string ledcode) {
            return base.Channel.DATCONV_getOVERDRAWN(ledcode);
        }
        
        public System.Threading.Tasks.Task<string> DATCONV_getOVERDRAWNAsync(string ledcode) {
            return base.Channel.DATCONV_getOVERDRAWNAsync(ledcode);
        }
        
        public System.Data.DataSet ReportsPortalDDL(string strsql) {
            return base.Channel.ReportsPortalDDL(strsql);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReportsPortalDDLAsync(string strsql) {
            return base.Channel.ReportsPortalDDLAsync(strsql);
        }
        
        public System.Data.DataSet ReportsPortalDML(string storedProcedure, string fromDate, string toDate, string bracode) {
            return base.Channel.ReportsPortalDML(storedProcedure, fromDate, toDate, bracode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReportsPortalDMLAsync(string storedProcedure, string fromDate, string toDate, string bracode) {
            return base.Channel.ReportsPortalDMLAsync(storedProcedure, fromDate, toDate, bracode);
        }
        
        public System.Data.DataSet ReportsPortalSQL(string connstr, string strsql) {
            return base.Channel.ReportsPortalSQL(connstr, strsql);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReportsPortalSQLAsync(string connstr, string strsql) {
            return base.Channel.ReportsPortalSQLAsync(connstr, strsql);
        }
        
        public System.Data.DataSet DATCONV_getUNPROCESSED(string dater) {
            return base.Channel.DATCONV_getUNPROCESSED(dater);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DATCONV_getUNPROCESSEDAsync(string dater) {
            return base.Channel.DATCONV_getUNPROCESSEDAsync(dater);
        }
        
        public System.Data.DataSet DATCONV_getREPORT29(string dater, string compcode) {
            return base.Channel.DATCONV_getREPORT29(dater, compcode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> DATCONV_getREPORT29Async(string dater, string compcode) {
            return base.Channel.DATCONV_getREPORT29Async(dater, compcode);
        }
        
        public System.Data.DataSet getCustomeronSMS(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code) {
            return base.Channel.getCustomeronSMS(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getCustomeronSMSAsync(string bra_code, string cus_num, string cur_code, string led_code, string sub_acct_code) {
            return base.Channel.getCustomeronSMSAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code);
        }
        
        public string DATCONV_getRESTIND(string cusnum) {
            return base.Channel.DATCONV_getRESTIND(cusnum);
        }
        
        public System.Threading.Tasks.Task<string> DATCONV_getRESTINDAsync(string cusnum) {
            return base.Channel.DATCONV_getRESTINDAsync(cusnum);
        }
        
        public string DATCONV_getDESENG(string code) {
            return base.Channel.DATCONV_getDESENG(code);
        }
        
        public System.Threading.Tasks.Task<string> DATCONV_getDESENGAsync(string code) {
            return base.Channel.DATCONV_getDESENGAsync(code);
        }
        
        public string DATCONV_getBracodeFromTellerId(string tellerid) {
            return base.Channel.DATCONV_getBracodeFromTellerId(tellerid);
        }
        
        public System.Threading.Tasks.Task<string> DATCONV_getBracodeFromTellerIdAsync(string tellerid) {
            return base.Channel.DATCONV_getBracodeFromTellerIdAsync(tellerid);
        }
        
        public bool CUSREM_delTxn() {
            return base.Channel.CUSREM_delTxn();
        }
        
        public System.Threading.Tasks.Task<bool> CUSREM_delTxnAsync() {
            return base.Channel.CUSREM_delTxnAsync();
        }
        
        public bool CUSREM_InsertTxn(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code, string cname) {
            return base.Channel.CUSREM_InsertTxn(bra_code, cus_num, cur_code, led_code, sub_acct_code, cname);
        }
        
        public System.Threading.Tasks.Task<bool> CUSREM_InsertTxnAsync(int bra_code, long cus_num, int cur_code, int led_code, int sub_acct_code, string cname) {
            return base.Channel.CUSREM_InsertTxnAsync(bra_code, cus_num, cur_code, led_code, sub_acct_code, cname);
        }
        
        public System.Data.DataSet CUSREM_getCustomerRecs() {
            return base.Channel.CUSREM_getCustomerRecs();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CUSREM_getCustomerRecsAsync() {
            return base.Channel.CUSREM_getCustomerRecsAsync();
        }
        
        public string CUSREM_process() {
            return base.Channel.CUSREM_process();
        }
        
        public System.Threading.Tasks.Task<string> CUSREM_processAsync() {
            return base.Channel.CUSREM_processAsync();
        }
        
        public string CUSREM_process2(long BRACODE, long CUSNUM, long CURCODE, long LEDCODE, long SUBACCTCODE) {
            return base.Channel.CUSREM_process2(BRACODE, CUSNUM, CURCODE, LEDCODE, SUBACCTCODE);
        }
        
        public System.Threading.Tasks.Task<string> CUSREM_process2Async(long BRACODE, long CUSNUM, long CURCODE, long LEDCODE, long SUBACCTCODE) {
            return base.Channel.CUSREM_process2Async(BRACODE, CUSNUM, CURCODE, LEDCODE, SUBACCTCODE);
        }
    }
}
